return {
  ["workshop-1185229307"]={ configuration_options={  }, enabled=true },
  ["workshop-1207269058"]={
    configuration_options={
      ddon=true,
      hbcolor="dynamic",
      hblength=10,
      hbpos=1,
      hbstyle="hidden",
      value=true 
    },
    enabled=true 
  },
  ["workshop-1271089343"]={
    configuration_options={ bekkitt_skeleton_pen=0, null_option=true, skeleton_player=true },
    enabled=true 
  },
  ["workshop-356435289"]={ configuration_options={ fishfarmrecipe="easy" }, enabled=true },
  ["workshop-361994110"]={
    configuration_options={ HAT_DECAY=false, RELEASE_BEES=false, SPRING_BEES=true },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-373653812"]={ configuration_options={  }, enabled=true },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=250 }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-396026892"]={ configuration_options={ OPT_DIFFICULTY=1 }, enabled=true },
  ["workshop-410900681"]={ configuration_options={  }, enabled=true },
  ["workshop-444235588"]={
    configuration_options={
      deluxeEndoFirepitBurnRate=0.75,
      deluxeFirepitBurnRate=0.75,
      dropLoot="yes",
      endoDropLoot="yes",
      heatStarBurnRate=0.9,
      heatStarDropLoot="yes",
      iceStarBurnRate=0.9,
      iceStarDropLoot="yes",
      recipeCost="standard",
      starsSpawnHounds="no" 
    },
    enabled=true 
  },
  ["workshop-458587300"]={ configuration_options={ Ownership=false, Travel_Cost=32 }, enabled=true },
  ["workshop-572538624"]={
    configuration_options={
      IS_CHS_ALL_MOD=true,
      IS_CHS_CHARACTER=true,
      IS_CHS_FIX_ALL=true,
      IS_CHS_SETTINGS=true 
    },
    enabled=true 
  },
  ["workshop-576950543"]={
    configuration_options={
      AMULET_DURABILITY="Infinite",
      ARMOR_DURABILITY="Infinite",
      AUTORETRAP=true,
      BEEFALO_DURABILITY="Infinite",
      BEEFALO_RUNSPEED="Default",
      BOOK_DURABILITY="Infinite",
      BOOMERANG_SPEED=10,
      BOOST_GOLD=false,
      CAMPING_DURABILITY="Infinite",
      CLOTHING_DURABILITY="Infinite",
      COMPASS_DURABILITY="Infinite",
      FIRESUPPRESSOR_DURABILITY="Infinite",
      GOLD_DURABILITY="Infinite",
      HEATROCK_DURABILITY="Infinite",
      ICEBOX_TUNING=0,
      LIGHT_DURABILITY="Infinite",
      PRIMARYTOOL_DURABILITY="Infinite",
      PROJECTILE_DURABILITY="Infinite",
      SEWINGKIT_DURABILITY="Infinite",
      STAFF_DURABILITY="Infinite",
      SWORD_DURABILITY="Infinite",
      TOOL_DURABILITY="Infinite",
      TORCH_DURABILITY="Infinite",
      TORCH_RADIUS=false,
      TRAP_DURABILITY="Infinite",
      WALL_DURABILITY="Default",
      WEAPON_DURABILITY="Infinite" 
    },
    enabled=true 
  },
  ["workshop-599498678"]={ configuration_options={  }, enabled=true },
  ["workshop-604761020"]={
    configuration_options={
      RUOYINXIAN=false,
      SHENGDANSHI=false,
      baoshibaolv=1,
      blue_baoshi=10,
      er_shuoming=0,
      green_baoshi=16,
      huangjinbaolv=3,
      marble_suipian=16,
      orange_baoshi=16,
      purple_baoshi=12,
      red_baoshi=16,
      shishengzhang=1,
      shitoubaolv=3,
      thulecite_xiukuang=16,
      wajuecishu=2,
      yellow_baoshi=12,
      yi_shuoming=0 
    },
    enabled=true 
  },
  ["workshop-622448972"]={
    configuration_options={
      health_enhance=false,
      health_regen=true,
      regen_value=50,
      wall_undeployable=false 
    },
    enabled=true 
  },
  ["workshop-655236052"]={
    configuration_options={
      ancientaltar="altar broken",
      antlers="enabled",
      armorskeleton="enabled",
      armorsnurtleshell="enabled",
      atriumkey="enabled",
      babybeefalo="disabled",
      batcave="disabled",
      beardhair="disabled",
      beehive="disabled",
      blueprint="enabled",
      butter="enabled",
      cactus="enabled",
      catcoonden="enabled",
      cave="yes",
      cavebananatree="enabled",
      chestereyebone="enabled",
      deerclopseyeball="enabled",
      dragonscales="enabled",
      flowercave="enabled",
      fossilpiece="enabled",
      furtuft="enabled",
      gears="enabled",
      gem="enabled",
      goosefeather="enabled",
      hivehat="enabled",
      honeycomb="enabled",
      houndmound="disabled",
      humanmeat="disabled",
      hutchfishbowl="enabled",
      klaussack="enabled",
      krampussack="enabled",
      lavaeegg="enabled",
      livinglog="enabled",
      lureplantbulb="enabled",
      mandrake="enabled",
      mandrakesoup="enabled",
      manrabbittail="enabled",
      marble="enabled",
      mermhouse="disabled",
      minotaurhorn="enabled",
      monkeybarrel="disabled",
      moonrocknugget="enabled",
      oasiscactus="enabled",
      oasislake="enabled",
      opalpreciousgem="enabled",
      opalstaff="enabled",
      petalsevil="enabled",
      pigtorch="enabled",
      pond="enabled",
      rabbithole="enabled",
      rareblueprint="enabled",
      reeds="enabled",
      resurrectionstone="disabled",
      royaljelly="enabled",
      sacredchest="enabled",
      shadowheart="enabled",
      shroomskin="enabled",
      sinkholesandstairs="disabled",
      skeletonhat="enabled",
      sketch="enabled",
      slurtlehat="enabled",
      slurtlehole="disabled",
      spidereggsack="enabled",
      spiderhat="enabled",
      spiderhole="disabled",
      statueglommer="disabled",
      steelwool="enabled",
      tallbirdnest="disabled",
      thulecitepieces="enabled",
      thurible="enabled",
      walruscamp="enabled",
      walrushat="enabled",
      wasphive="disabled",
      wormlight="enabled",
      wormlightplant="enabled" 
    },
    enabled=true 
  },
  ["workshop-661253977"]={
    configuration_options={ amudiao=false, baodiao=0, kong=0, rendiao=0, zbdiao=false },
    enabled=true 
  },
  ["workshop-687193679"]={
    configuration_options={ twigs_to_create=10, twigs_to_create_a_log=1 },
    enabled=true 
  },
  ["workshop-758532836"]={
    configuration_options={
      AUTOPAUSECONSOLE=true,
      AUTOPAUSEMAP=true,
      AUTOPAUSESINGLEPLAYERONLY=true,
      ENABLECLIENTPAUSE=false,
      ENABLEHOTKEY=true,
      KEYBOARDTOGGLEKEY="P" 
    },
    enabled=true 
  },
  ["workshop-786556008"]={
    configuration_options={ ENABLEBACKPACK=false, EXTRASLOT=0, INVENTORYSIZE=45 },
    enabled=true 
  },
  ["workshop-817025783"]={ configuration_options={  }, enabled=true },
  ["workshop-842821674"]={ configuration_options={ ["Logs burn into charcoal"]=true }, enabled=true },
  ["workshop-858801295"]={
    configuration_options={ config_fuel_max=150, config_recipe=1, config_spawn_time=15 },
    enabled=true 
  } 
}